apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  rules:
    - host: {{ .Values.name }}.{{ .Values.IngressDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.HTTP_PORT }}