apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.name }}
spec:
  ports:
  - name: schema-registry
    port: {{ .Values.HTTP_PORT }}
    targetPort: {{ .Values.HTTP_PORT }}
  selector:
    app: {{ .Values.name }}